services:
  warehouse-service:
    container_name: warehouse-service
    build: ./warehouse-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - kafka
      - client-service
    expose:
      - "80"
    restart: always

  user-service:
    container_name: user-service
    build: ./user-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - client-service
    expose:
      - "80"
    restart: always

  client-service:
    container_name: client-service
    build: ./client-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    expose:
      - "80"
    restart: always

  auth-service:
    container_name: auth-service
    build: ./auth-service
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - redis
    expose:
      - "80"

  cart-service:
    container_name: cart-service
    build: ./cart-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - user-service
      - warehouse-service
    expose:
      - "80"
    restart: always

  order-service:
    container_name: order-service
    build: ./order-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - warehouse-service
    expose:
      - "80"
    restart: always

  search-service:
    container_name: search-service
    build: ./search-service
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - warehouse-service
      - redis
    expose:
      - "80"
    restart: always

  request-service:
    container_name: request-service
    build: ./request-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - warehouse-service
    expose:
      - "80"
    restart: always

  report-service:
    container_name: report-service
    build: ./report-service
    environment:
      - ENV=dev
    networks:
      - app-network
    extra_hosts:
      - "postgres:176.57.221.144"
    depends_on:
      - order-service
    expose:
      - "80"
    restart: always

  notifier-service:
    container_name: notifier-service
    build: ./notifier-service
    environment:
      - ENV=dev
    networks:
      - app-network
    expose:
      - "80"
        
  route-search-service:
    container_name: route-search-service
    build: ./route-search-service
    environment:
      - ENV=dev
    networks:
      - app-network
    expose:
      - "80"

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    networks:
      - app-network
    expose:
      - "80"

  redis:
    hostname: redis
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 1
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - app-network

  kafka:
    hostname: kafka
    image: confluentinc/cp-server:7.7.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29091, PLAINTEXT_HOST://kafka:9091
    ports:
      - "9091:9091"
    networks:
      - app-network
    depends_on:
      - zookeeper
    restart: always

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9020:8080"
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29091,
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_db_data:
