services:
  warehouse-service:
    hostname: warehouse-service
    build: ./warehouse-service
    ports:
      - "8081:8080"
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - postgres
      - kafka
      - client-service
    restart: always

  user-service:
    hostname: user-service
    build: ./user-service
    ports:
      - "8082:8080"
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - postgres
      - client-service
    restart: always

  client-service:
    hostname: client-service
    build: ./client-service
    ports:
      - "8083:8080"
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always

  auth-service:
    hostname: auth-service
    build: ./auth-service
    ports:
      - "8084:8080"
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - redis

  api-gateway:
    hostname: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    networks:
      - app-network

  redis:
    hostname: redis
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    hostname: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    hostname: kafka
    image: confluentinc/cp-server:7.7.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29091, PLAINTEXT_HOST://kafka:9091
    ports:
      - "9091:9091"
    networks:
      - app-network
    depends_on:
      - zookeeper
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 1
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
